#!/bin/bash
#
# configuration-dialog.sh
# this file is part of the mysql-ha suite
# Copyright (C) 2002 Fernando Ipar. see the file COPYING for more info. 

#
# asks the user for the configuration keys one by one, providing 
# default values when applicable
#

clear


. $MYSQLHA_HOME/compat.sh

. $BASHRC

msgbox()
{
dialog --msgbox "$*" 20 60
}

inputbox()
{
dialog  --inputbox "$1" 20 40 "$2" 2> output.$$
}

msgbox "$(cat msg/$lang/welcome)"

FIL=/etc/mysql-ha.conf

user=$USER
host=$HOSTNAME
datetime=$(date "+%m-%d-%Y %H:%M:%S")

cat <<EONOTICE >$FIL
#mysql-la configuration file
#this file was automatically generated by configuration-menu.sh for ${user}@${host} at $datetime
#do not modify manually if you don't read the documentation first
#see man/info mysql-ha


EONOTICE

inputbox "$(cat msg/$lang/CLUSTER_IP)"
echo "CLUSTER_IP=$(cat output.$$)" >>$FIL;echo

inputbox "$(cat msg/$lang/CLUSTER_NETMASK)"
echo "CLUSTER_NETMASK=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/CLUSTER_BROADCAST)"
echo "CLUSTER_BROADCAST=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/CLUSTER_DEVICE)"
echo "CLUSTER_DEVICE=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/MYSQL_USER)" "selector"
echo "MYSQL_USER=$(cat output.$$)" >> $FIL;echo

msgbox "$(cat msg/$lang/SECURITY_WARNING)"

inputbox "$(cat msg/$lang/MYSQL_PASSWORD)" "selector"
echo "MYSQL_PASSWORD=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/REPLICATION_USER)" "replicator"
echo "REPLICATION_USER=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/REPLICATION_PASSWORD)" "replicatorpwd"
echo "REPLICATION_PASSWORD=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/MYSQL_DATABASE)" "test"
echo "MYSQL_DATABASE=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/ARP_DELAY)" 5
echo "ARP_DELAY=$(cat output.$$)" >> $FIL;echo

#while [ -z "$DEFAULT_MAC_ADDR" ]; do
#	echo -n "DEFAULT_MAC_ADDR: "; read DEFAULT_MAC_ADDR
#done
#echo "DEFAULT_MAC_ADDR=$DEFAULT_MAC_ADDR" >> $FIL

inputbox "$(cat msg/$lang/MASTER_SLEEP_TIME)" 60
echo "MASTER_SLEEP_TIME=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/SLAVE_SLEEP_TIME)" 60
echo "SLAVE_SLEEP_TIME=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/SSH_PATIENCE)" 20
echo "SSH_PATIENCE=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/MONITOR_PATIENCE)" 10
echo "MONITOR_PATIENCE=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/MONITOR_CHK_THRESHOLD)" 20
echo "MONITOR_CHK_THRESHOLD=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/MYSQL_KILL_WAIT)" 5
echo "MYSQL_KILL_WAIT=$(output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/MYSQL_RESTART_WAIT)" 5
echo "MYSQL_RESTART_WAIT=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/FPING_ATTEMPTS)" 3
echo "FPING_ATTEMPTS=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/SLAVE)"
echo "SLAVE=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/SIG_KILL_WAIT)" 5
echo "SIG_KILL_WAIT=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/DB_USER)" root
echo "DB_USER=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/DB_PASSWORD)" rootpwd
echo "DB_PASSWORD=$(cat output.$$)" >> $FIL;echo

inputbox "$(cat msg/$lang/NOTIFY_EMAIL)" root@localhost
echo "NOTIFY_EMAIL=$(cat output.$$)" >> $FIL;echo

chown -v root.root $FIL
chmod -v 600 $FIL


[ -n "$N_SLAVE" -o -n "$N_MASTER" ] && {
	msgbox "The system is configured!"
	exit 0
}

echo "adding $MYSQLHA_HOME/role.include to $BASHRC" 
grep "$MYSQLHA_HOME/role.include" $BASHRC >/dev/null || {
	echo ". $MYSQLHA_HOME/role.include" >> $BASHRC
	echo >> $BASHRC
	}

NODE=2
echo
while [ $NODE -ne 0 -a $NODE -ne 1 ] ; do
	dialog --menu 'Almost done, now enter the role of this master' 16 22 10 '0' 'Master' '1' 'Slave' >output.$$
	NODE=$(cat output.$$)
	[ $NODE -eq 0 ] && cp -f $MYSQLHA_HOME/master.include $MYSQLHA_HOME/role.include
	[ $NODE -eq 1 ] && cp -f $MYSQLHA_HOME/slave.include $MYSQLHA_HOME/role.include
done

msgbox "The system is configured!"
