#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# generated by wxGlade 0.4.1 on Wed Oct 11 02:16:59 2006

import wx

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.L_CLUSTER_IP = wx.StaticText(self, -1, "CLUSTER_IP")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "")
        self.L_CLUSTER_NETMASK = wx.StaticText(self, -1, "CLUSTER_NETMASK")
        self.text_ctrl_1_copy_2 = wx.TextCtrl(self, -1, "")
        self.L_CLUSTER_BROADCAST = wx.StaticText(self, -1, "CLUSTER_BROADCAST")
        self.text_ctrl_1_copy_3 = wx.TextCtrl(self, -1, "")
        self.L_CLUSTER_DEVICE = wx.StaticText(self, -1, "CLUSTER_DEVICE")
        self.text_ctrl_1_copy_4 = wx.TextCtrl(self, -1, "")
        self.L_MYSQL_USER = wx.StaticText(self, -1, "MYSQL_USER")
        self.text_ctrl_1_copy_5 = wx.TextCtrl(self, -1, "")
        self.L_MYSQL_PASSWORD = wx.StaticText(self, -1, "MYSQL_PASSWORD")
        self.text_ctrl_1_copy_6 = wx.TextCtrl(self, -1, "")
        self.L_REPLICATION_USER = wx.StaticText(self, -1, "REPLICATION_USER")
        self.text_ctrl_1_copy_1 = wx.TextCtrl(self, -1, "")
        self.L_REPLICATION_PASSWORD = wx.StaticText(self, -1, "REPLICATION_PASSWORD")
        self.text_ctrl_1_copy_7 = wx.TextCtrl(self, -1, "")
        self.L_MYSQL_DATABASE = wx.StaticText(self, -1, "MYSQL_DATABASE")
        self.text_ctrl_1_copy_8 = wx.TextCtrl(self, -1, "")
        self.L_ARP_DELAY = wx.StaticText(self, -1, "ARP_DELAY")
        self.text_ctrl_1_copy_9 = wx.TextCtrl(self, -1, "")
        self.L_MASTER_SLEEP_TIME = wx.StaticText(self, -1, "MASTER_SLEEP_TIME")
        self.text_ctrl_1_copy = wx.TextCtrl(self, -1, "")
        self.L_SLAVE_SLEEP_TIME = wx.StaticText(self, -1, "SLAVE_SLEEP_TIME")
        self.text_ctrl_1_copy_10 = wx.TextCtrl(self, -1, "")
        self.L_SSH_PATIENCE = wx.StaticText(self, -1, "SSH_PATIENCE")
        self.text_ctrl_1_copy_11 = wx.TextCtrl(self, -1, "")
        self.L_MONITOR_PATIENCE = wx.StaticText(self, -1, "MONITOR_PATIENCE")
        self.text_ctrl_1_copy_12 = wx.TextCtrl(self, -1, "")
        self.L_MONITOR_CHK_THRESHOLD = wx.StaticText(self, -1, "MONITOR_CHK_THRESHOLD")
        self.text_ctrl_1_copy_13 = wx.TextCtrl(self, -1, "")
        self.L_MYSQL_KILL_WAIT = wx.StaticText(self, -1, "MYSQL_KILL_WAIT")
        self.text_ctrl_1_copy_14 = wx.TextCtrl(self, -1, "")
        self.L_MYSQL_RESTART_WAIT = wx.StaticText(self, -1, "MYSQL_RESTART_WAIT")
        self.text_ctrl_1_copy_15 = wx.TextCtrl(self, -1, "")
        self.L_FPING_ATTEMPTS = wx.StaticText(self, -1, "FPING_ATTEMPTS")
        self.text_ctrl_1_copy_16 = wx.TextCtrl(self, -1, "")
        self.L_SLAVE = wx.StaticText(self, -1, "SLAVE")
        self.text_ctrl_1_copy_17 = wx.TextCtrl(self, -1, "")
        self.L_SIG_KILL_WAIT = wx.StaticText(self, -1, "SIG_KILL_WAIT")
        self.text_ctrl_1_copy_18 = wx.TextCtrl(self, -1, "")
        self.L_DB_USER = wx.StaticText(self, -1, "DB_USER")
        self.text_ctrl_1_copy_19 = wx.TextCtrl(self, -1, "")
        self.L_DB_PASSWORD = wx.StaticText(self, -1, "DB_PASSWORD")
        self.text_ctrl_1_copy_20 = wx.TextCtrl(self, -1, "")
        self.L_NOTIFY_EMAIL = wx.StaticText(self, -1, "NOTIFY_EMAIL")
        self.text_ctrl_1_copy_21 = wx.TextCtrl(self, -1, "")
        self.Save = wx.Button(self, -1, "Save config")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.DoSaveConfig, self.Save)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame_1")
        self.text_ctrl_1.SetMinSize((380, 25))
        self.text_ctrl_1_copy_2.SetMinSize((380, 25))
        self.text_ctrl_1_copy_3.SetMinSize((380, 25))
        self.text_ctrl_1_copy_4.SetMinSize((380, 25))
        self.text_ctrl_1_copy_5.SetMinSize((380, 25))
        self.text_ctrl_1_copy_6.SetMinSize((380, 25))
        self.text_ctrl_1_copy_1.SetMinSize((380, 25))
        self.text_ctrl_1_copy_7.SetMinSize((380, 25))
        self.text_ctrl_1_copy_8.SetMinSize((380, 25))
        self.text_ctrl_1_copy_9.SetMinSize((380, 25))
        self.text_ctrl_1_copy.SetMinSize((380, 25))
        self.text_ctrl_1_copy_10.SetMinSize((380, 25))
        self.text_ctrl_1_copy_11.SetMinSize((380, 25))
        self.text_ctrl_1_copy_12.SetMinSize((380, 25))
        self.text_ctrl_1_copy_13.SetMinSize((380, 25))
        self.text_ctrl_1_copy_14.SetMinSize((380, 25))
        self.text_ctrl_1_copy_15.SetMinSize((380, 25))
        self.text_ctrl_1_copy_16.SetMinSize((380, 25))
        self.text_ctrl_1_copy_17.SetMinSize((380, 25))
        self.text_ctrl_1_copy_18.SetMinSize((380, 25))
        self.text_ctrl_1_copy_19.SetMinSize((380, 25))
        self.text_ctrl_1_copy_20.SetMinSize((380, 25))
        self.text_ctrl_1_copy_21.SetMinSize((380, 25))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(28, 2, 0, 0)
        grid_sizer_1.Add(self.L_CLUSTER_IP, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_CLUSTER_NETMASK, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_2, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_CLUSTER_BROADCAST, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_3, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_CLUSTER_DEVICE, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_4, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MYSQL_USER, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_5, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MYSQL_PASSWORD, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_6, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_REPLICATION_USER, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_1, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_REPLICATION_PASSWORD, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_7, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MYSQL_DATABASE, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_8, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_ARP_DELAY, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_9, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MASTER_SLEEP_TIME, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_SLAVE_SLEEP_TIME, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_10, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_SSH_PATIENCE, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_11, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MONITOR_PATIENCE, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_12, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MONITOR_CHK_THRESHOLD, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_13, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MYSQL_KILL_WAIT, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_14, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_MYSQL_RESTART_WAIT, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_15, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_FPING_ATTEMPTS, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_16, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_SLAVE, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_17, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_SIG_KILL_WAIT, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_18, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_DB_USER, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_19, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_DB_PASSWORD, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_20, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.L_NOTIFY_EMAIL, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.text_ctrl_1_copy_21, 0, wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.Save, 0, wx.ADJUST_MINSIZE, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def DoSaveConfig(self, event): # wxGlade: MyFrame.<event_handler>
        print "Event handler `DoSaveConfig' not implemented!"
        event.Skip()

# end of class MyFrame


class Configuration(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class Configuration

if __name__ == "__main__":
    configurationWxpython = Configuration(0)
    configurationWxpython.MainLoop()
