#!/bin/bash
#
# configuration-menu.sh
# this file is part of the mysql-ha suite
# Copyright (C) 2002 Fernando Ipar. see the file COPYING for more info. 

#
# asks the user for the configuration keys one by one, providing 
# default values when applicable
#

clear

. $MYSQLHA_HOME/compat.sh

. $BASHRC


cat msg/welcome

FIL=/etc/mysql-ha.conf

user=$USER
host=$HOSTNAME
datetime=$(date "+%m-%d-%Y %H:%M:%S")

cat <<EONOTICE>$FIL
#mysq-la configuration file
#this file was automatically generated by configuration-menu.sh for ${user}@{$host} at $datetime
#do not modify manually if you don't read the documentation first
#see man/info mysql-ha


EONOTICE

cat msg/CLUSTER_IP
while [ -z "$CLUSTER_IP" ]; do
	echo -n "CLUSTER_IP: "; read CLUSTER_IP
done
echo "CLUSTER_IP=$CLUSTER_IP" >>$FIL;echo

cat msg/CLUSTER_NETMASK
while [ -z "$CLUSTER_NETMASK" ]; do
	echo -n "CLUSTER_NETMASK: "; read CLUSTER_NETMASK
done
echo "CLUSTER_NETMASK=$CLUSTER_NETMASK" >> $FIL;echo

cat msg/CLUSTER_BROADCAST
while [ -z "$CLUSTER_BROADCAST" ]; do
	echo -n "CLUSTER_BROADCAST: "; read CLUSTER_BROADCAST
done
echo "CLUSTER_BROADCAST=$CLUSTER_BROADCAST" >> $FIL;echo

cat msg/CLUSTER_DEVICE
while [ -z "$CLUSTER_DEVICE" ]; do
	echo -n "CLUSTER_DEVICE: [eth0] "; read CLUSTER_DEVICE; [ -z "$CLUSTER_DEVICE" ] && CLUSTER_DEVICE=eth0
done
echo "CLUSTER_DEVICE=$CLUSTER_DEVICE" >> $FIL;echo

cat msg/MYSQL_USER
while [ -z "$MYSQL_USER" ]; do
	echo -n "MYSQL_USER: [ANONYMOUS] "; read MYSQL_USER; [ -z "$MYSQL_USER" ] && MYSQL_USER=ANONYMOUS
done
echo "MYSQL_USER=$MYSQL_USER" >> $FIL;echo

cat msg/MYSQL_PASSWORD
cat msg/SECURITY_WARNING

while [ -z "$MYSQL_PASSWORD" ]; do
	echo -n "MYSQL_PASSWORD: [] "; read MYSQL_PASSWORD; [ -z "$MYSQL_PASSWORD" ] && MYSQL_PASSWORD=
done
echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> $FIL;echo


cat msg/REPLICATION_USER
while [ -z "$REPLICATION_USER" ]; do
	echo -n "REPLICATION_USER: [replicator] "; read REPLICATION_USER; [ -z "$REPLICATION_USER" ] && REPLICATION_USER=replicator
done
echo "REPLICATION_USER=$REPLICATION_USER" >> $FIL;echo

cat msg/REPLICATION_PASSWORD
cat msg/SECURITY_WARNING

while [ -z "$REPLICATION_PASSWORD" ]; do
	echo -n "REPLICATION_PASSWORD: [replicatorpwd] "; read REPLICATION_PASSWORD; [ -z "$REPLICATION_PASSWORD" ] && REPLICATION_PASSWORD=replicatorpwd
done
echo "REPLICATION_PASSWORD=$REPLICATION_PASSWORD" >> $FIL;echo

cat msg/MYSQL_DATABASE
while [ -z "$MYSQL_DATABASE" ]; do
	echo -n "MYSQL_DATABASE: [testdb] "; read MYSQL_DATABASE; [ -z "$MYSQL_DATABASE" ] && MYSQL_DATABASE=testdb
done
echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> $FIL;echo

cat msg/ARP_DELAY
while [ -z "$ARP_DELAY" ]; do
	echo -n "ARP_DELAY: [5] "; read ARP_DELAY; [ -z "$ARP_DELAY" ] && ARP_DELAY=5
done
echo "ARP_DELAY=$ARP_DELAY" >> $FIL;echo

#while [ -z "$DEFAULT_MAC_ADDR" ]; do
#	echo -n "DEFAULT_MAC_ADDR: "; read DEFAULT_MAC_ADDR
#done
#echo "DEFAULT_MAC_ADDR=$DEFAULT_MAC_ADDR" >> $FIL

cat msg/MASTER_SLEEP_TIME
while [ -z "$MASTER_SLEEP_TIME" ]; do
	echo -n "MASTER_SLEEP_TIME: [60] "; read MASTER_SLEEP_TIME; [ -z "$MASTER_SLEEP_TIME" ] && MASTER_SLEEP_TIME=60
done
echo "MASTER_SLEEP_TIME=$MASTER_SLEEP_TIME" >> $FIL;echo

cat msg/SLAVE_SLEEP_TIME
while [ -z "$SLAVE_SLEEP_TIME" ]; do
	echo -n "SLAVE_SLEEP_TIME: [60] "; read SLAVE_SLEEP_TIME; [ -z "$SLAVE_SLEEP_TIME" ] && SLAVE_SLEEP_TIME=60
done
echo "SLAVE_SLEEP_TIME=$SLAVE_SLEEP_TIME" >> $FIL;echo

cat msg/SSH_PATIENC
while [ -z "$SSH_PATIENCE" ]; do
	echo -n "SSH_PATIENCE: [20] "; read SSH_PATIENCE; [ -z "$SSH_PATIENCE" ] && SSH_PATIENCE=20
done
echo "SSH_PATIENCE=$SSH_PATIENCE" >> $FIL;echo

cat msg/MONITOR_PATIENCE
while [ -z "$MONITOR_PATIENCE" ]; do
	echo -n "MONITOR_PATIENCE: [10] "; read MONITOR_PATIENCE; [ -z "$MONITOR_PATIENCE" ] && MONITOR_PATIENCE=10
done
echo "MONITOR_PATIENCE=$MONITOR_PATIENCE" >> $FIL;echo

cat msg/MONITOR_CHK_THRESHOLD
while [ -z "$MONITOR_CHK_THRESHOLD" ]; do
	echo -n "MONITOR_CHK_THRESHOLD: [20] "; read MONITOR_CHK_THRESHOLD; [ -z "$MONITOR_CHK_THRESHOLD" ] && MONITOR_CHK_THRESHOLD=20
done
echo "MONITOR_CHK_THRESHOLD=$MONITOR_CHK_THRESHOLD" >> $FIL;echo

cat msg/MYSQL_KILL_WAIT
while [ -z "$MYSQL_KILL_WAIT" ]; do
	echo -n "MYSQL_KILL_WAIT: [5] "; read MYSQL_KILL_WAIT; [ -z "$MYSQL_KILL_WAIT" ] && MYSQL_KILL_WAIT=5
done
echo "MYSQL_KILL_WAIT=$MYSQL_KILL_WAIT" >> $FIL;echo

cat msg/MYSQL_RESTART_WAIT
while [ -z "$MYSQL_RESTART_WAIT" ]; do
	echo -n "MYSQL_RESTART_WAIT: [5] "; read MYSQL_RESTART_WAIT; [ -z "$MYSQL_RESTART_WAIT" ] && MYSQL_RESTART_WAIT=5
done
echo "MYSQL_RESTART_WAIT=$MYSQL_RESTART_WAIT" >> $FIL;echo

cat msg/FPING/ATTEMPTS
while [ -z "$FPING_ATTEMPTS" ]; do
	echo -n "FPING_ATTEMPTS: [3] "; read FPING_ATTEMPTS; [ -z "$FPING_ATTEMPTS" ] && FPING_ATTEMPTS=3
done
echo "FPING_ATTEMPTS=$FPING_ATTEMPTS" >> $FIL;echo

cat msg/SLAVE
while [ -z "$SLAVE" ]; do
	echo -n "SLAVE: [mysql-slave] "; read SLAVE; [ -z "$SLAVE" ] && SLAVE=mysql-slave
done
echo "SLAVE=$SLAVE" >> $FIL;echo

cat msg/SIG_KILL_WAIT
while [ -z "$SIG_KILL_WAIT" ]; do
	echo -n "SIG_KILL_WAIT: [5] "; read SIG_KILL_WAIT; [ -z "$SIG_KILL_WAIT" ] && SIG_KILL_WAIT=5
done
echo "SIG_KILL_WAIT=$SIG_KILL_WAIT" >> $FIL;echo

cat msg/DB_USER
while [ -z "$DB_USER" ]; do
	echo -n "DB_USER: [root] "; read DB_USER; [ -z "$DB_USER" ] && DB_USER=root
done
echo "DB_USER=$DB_USER" >> $FIL;echo

cat msg/DB_PASSWORD
cat msg/SECURITY_WARNING

while [ -z "$DB_PASSWORD" ]; do
	echo -n "DB_PASSWORD: [rootpwd] "; read DB_PASSWORD; [ -z "$DB_PASSWORD" ] && export DB_PASSWORD=rootpwd
done
echo "DB_PASSWORD=$DB_PASSWORD" >> $FIL;echo

cat msg/NOTIFY_EMAIL
while [ -z "$NOTIFY_EMAIL" ]; do
	echo -n "NOTIFY_EMAIL: [root@localhost] "; read NOTIFY_EMAIL; [ -z "$NOTIFY_EMAIL" ] && export NOTIFY_EMAIL=root@localhost
done
echo "NOTIFY_EMAIL=$NOTIFY_EMAIL" >> $FIL;echo

chown -v root.root $FIL
chmod -v 600 $FIL


[ -n "$N_SLAVE" -o -n "$N_MASTER" ] && {
	echo done
	exit 0
}

echo "adding $MYSQLHA_HOME/role.include to $BASHRC" >> $FIL;echo 
grep "$MYSQLHA_HOME/role.include" $BASHRC >/dev/null || {
	echo ". $MYSQLHA_HOME/role.include" >> $BASHRC
	echo >> $BASHRC
	}

NODE=2
echo
while [ $NODE -ne 0 -a $NODE -ne 1 ] ; do
	echo "almost done, now enter 0 if this node is the master, or 1 if it is the slave: "; read NODE
	[ $NODE -eq 0 ] && cp -f $MYSQLHA_HOME/master.include $MYSQLHA_HOME/role.include
	[ $NODE -eq 1 ] && cp -f $MYSQLHA_HOME/slave.include $MYSQLHA_HOME/role.include
done

echo "done"
