#!/bin/bash
#
# pwrap
# this file is part of the highbase suite
# Copyright 2002 Fernando Ipar - fipar@acm.org / fipar@users.sourceforge.net

# This program is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation;
# either version 2 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330,
# Boston, MA 02111-1307 USA

# untidy hack to get the safe_cmd.sh and it's wrapper to work
# If i don't use this, then wrapper_safe_cmd.sh will wait for
# TIMEOUT seconds even if the program exits normally
# after 2ms, plus, it wont tell me about the exit code of the
# program. 
# pwrap does a kill -SIGTERM on PPID if retval is 0, or
# -SIGKILL if otherwise
# We need to do different kills to let wrapper_safe_cmd know
# if the command finished successfully or not. See that 
# script's code for more info

eval $* 2>&1
[ $? -ne 0 ] && kill -9 $PPID || kill $PPID

